# Generated by Django 4.1.4 on 2023-06-26 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rsvp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('goal', models.IntegerField()),
                ('background_photo', models.URLField(verbose_name='Link to Background Photo')),
            ],
        ),
        migrations.CreateModel(
            name='Registry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex. "Kitchen", or "Appliances"', max_length=200)),
                ('visible', models.BooleanField(default=False, verbose_name='Visible on Site (Published)')),
            ],
            options={
                'verbose_name_plural': 'Registries',
            },
        ),
        migrations.CreateModel(
            name='RegistryItem',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('url', models.URLField(verbose_name='Link to Purchasing Site')),
                ('photo_url', models.URLField(verbose_name='Photo URL')),
                ('price', models.IntegerField(blank=True, null=True)),
                ('claimer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claimed_items', to='rsvp.invite')),
                ('registry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registry_items', to='registry.registry')),
            ],
        ),
        migrations.CreateModel(
            name='FundContrib',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Contribution Amount')),
                ('contributer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_contribs', to='rsvp.invite')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='registry.fund')),
            ],
            options={
                'verbose_name': 'Fund Contribution',
                'verbose_name_plural': 'Fund Contributions',
            },
        ),
    ]
