# Generated by Django 4.1.4 on 2022-12-19 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registry',
            options={'verbose_name_plural': 'Registries'},
        ),
    ]
