# Generated by Django 4.1.4 on 2022-12-31 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0002_invite_email'),
        ('registry', '0003_alter_registryitem_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registryitem',
            name='claimer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claimed_items', to='rsvp.guest'),
        ),
    ]
