# Generated by Django 4.1.4 on 2022-12-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_alter_registryitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registryitem',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
