# Generated by Django 4.1.4 on 2023-02-01 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0006_fundcontrib'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundcontrib',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Contribution Amount'),
            preserve_default=False,
        ),
    ]
