# Generated by Django 4.1.4 on 2023-02-25 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0007_fundcontrib_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FundContrib',
        ),
    ]
