# Generated by Django 4.1.4 on 2023-02-26 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0010_fund_background_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='goal',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
