# Generated by Django 4.1.4 on 2023-02-27 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0012_alter_registryitem_claimer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fundcontrib',
            options={'verbose_name': 'Fund Contribution', 'verbose_name_plural': 'Fund Contributions'},
        ),
        migrations.AddField(
            model_name='registryitem',
            name='photo_url',
            field=models.URLField(default='https://images.unsplash.com/photo-1550237330-a5d774594098?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80', verbose_name='Photo URL'),
            preserve_default=False,
        ),
    ]
