# Generated by Django 4.1.4 on 2022-12-31 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_registryitem_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registryitem',
            name='url',
            field=models.URLField(verbose_name='Link to Purchasing Site'),
        ),
    ]
