# Generated by Django 4.1.4 on 2022-12-31 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_alter_registryitem_claimer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registryitem',
            name='picture',
        ),
    ]
