# Generated by Django 4.1.4 on 2023-02-01 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0002_invite_email'),
        ('registry', '0005_remove_registryitem_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundContrib',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rsvp.invite')),
            ],
        ),
    ]
