# Generated by Django 4.1.4 on 2023-02-25 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0009_fund_fundcontrib'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='background_photo',
            field=models.URLField(default='', verbose_name='Link to Background Photo'),
            preserve_default=False,
        ),
    ]
