# Generated by Django 4.1.4 on 2023-02-25 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0003_fund_invite_funds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='funds',
        ),
        migrations.DeleteModel(
            name='Fund',
        ),
    ]
