# Generated by Django 4.1.4 on 2023-02-26 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0004_remove_invite_funds_delete_fund'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invite',
            name='uuid',
            field=models.UUIDField(editable=False, unique=True),
        ),
    ]
