# Generated by Django 4.1.4 on 2023-02-26 02:23

from django.db import migrations, models
import rsvp.models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0006_remove_invite_id_invite_pseudo_id_alter_invite_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='pseudo_id',
            field=models.IntegerField(default=rsvp.models.next_id, unique=True),
        ),
    ]
