# Generated by Django 4.1.4 on 2023-03-03 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0008_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='email',
        ),
    ]
