# Generated by Django 4.1.4 on 2023-03-19 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0010_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name_plural': 'Guest Summary'},
        ),
        migrations.AddField(
            model_name='guest',
            name='is_child',
            field=models.BooleanField(default=False, verbose_name='Is a child'),
            preserve_default=False,
        ),
    ]
