# Generated by Django 4.1.4 on 2022-12-24 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('family_name', models.CharField(max_length=200)),
                ('uuid', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('invite_url', models.URLField(verbose_name='Unique RSVP Link')),
                ('finished', models.BooleanField(default=False, verbose_name='Has Completed RSVP')),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dietary_restrictions', models.CharField(blank=True, max_length=200, null=True)),
                ('is_attending', models.BooleanField(blank=True, null=True, verbose_name='Is Attending')),
                ('invite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='rsvp.invite')),
            ],
        ),
    ]
