# Generated by Django 4.1.4 on 2022-12-31 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='email',
            field=models.EmailField(default='you@example.com', max_length=254, verbose_name='Email Address'),
            preserve_default=False,
        ),
    ]
