# Generated by Django 4.1.4 on 2022-12-18 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='invite_url',
            field=models.URLField(default='https://idowithliu.com/rsvp?userID=<django.db.models.fields.UUIDField>', verbose_name='Unique RSVP Link'),
        ),
    ]
