# Generated by Django 4.1.4 on 2022-12-18 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0002_invite_invite_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='invite_url',
            field=models.URLField(verbose_name='Unique RSVP Link'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='uuid',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
