# Generated by Django 4.1.4 on 2022-12-19 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0003_alter_invite_invite_url_alter_invite_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='is_attending',
            field=models.BooleanField(blank=True, null=True, verbose_name='Is Attending'),
        ),
        migrations.AddField(
            model_name='invite',
            name='finished',
            field=models.BooleanField(blank=True, null=True, verbose_name='Has Completed RSVP'),
        ),
    ]
