# Generated by Django 4.1.4 on 2022-12-19 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0004_guest_is_attending_invite_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='finished',
            field=models.BooleanField(default=False, verbose_name='Has Completed RSVP'),
        ),
    ]
