# Generated by Django 4.1.4 on 2023-02-26 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0005_invite_id_alter_invite_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='id',
        ),
        migrations.AddField(
            model_name='invite',
            name='pseudo_id',
            field=models.IntegerField(default=1, unique=True),
        ),
        migrations.AlterField(
            model_name='invite',
            name='uuid',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
