# Generated by Django 4.1.4 on 2022-12-20 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0005_alter_invite_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
