# Generated by Django 4.1.4 on 2023-03-07 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0009_remove_invite_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
