# Generated by Django 4.1.4 on 2022-12-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.CharField(default='yes', max_length=200),
            preserve_default=False,
        ),
    ]
